import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local"
import {Heebo,Inter}from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";


const heebo =Heebo({subsets:["latin"], weight:["400","700","900"]});
const inter =Heebo({subsets:["latin"], weight:["400","700"]});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={heebo.className}>
        
      <Navbar font = {inter} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
